FROM python:3.11.5-alpine3.18

RUN adduser -S app
RUN addgroup app && addgroup app app

WORKDIR /app

RUN apk add curl
RUN curl -sSL https://install.python-poetry.org | python3 - --version 1.6.1
ENV POETRY_VIRTUALENVS_CREATE=false

COPY poetry.lock pyproject.toml ./

RUN /root/.local/share/pypoetry/venv/bin/poetry install

COPY . .
